#!/usr/bin/env bash

function sha512(){
    sha512sum "$file"
}
function sha256(){
    sha256sum "$file"
}
function sha1(){
    sha1sum "$file"
}
function md5(){
    md5sum "$file"
}

function print_sums() {
    for file in $path
    do
        echo ""
        echo "==> Sums for \"$file\""
        echo "==> MD5"
        md5
        echo "==> SHA1"
        sha1
        echo "==> SHA256"
        sha256
        echo "==> SHA512"
        sha512
        echo ""
    done
}

function main() {
    path=$1
    if [ -z "$path" ]
    then
        read -p "What would you like to find the sum for? " path
	print_sums
    else
        until [ -z "$1" ]
        do
            path=$1
            print_sums
            shift
        done
    fi
}

main "$@"
