#!/bin/bash

function sha512(){
  echo "Generating SHA512 sum..."
  sha512sum "$sumdo"
}
function sha256(){
  echo "Generating SHA256 sum..."
  sha256sum "$sumdo"
}
function sha1(){
  echo "Generating SHA1 sum..."
  sha1sum "$sumdo"
}
function md5(){
  echo "Generating MD5 sum..."
  md5sum "$sumdo"
}

file=$1
if [ -z "$file" ]
then
  echo "Filename not provided."
  read -p "What would you like to find the sum for? " file
  for sumdo in $file
  do
    echo ""
    echo "################################################################################"
    echo "Sums for $sumdo"
    md5
    sha1
    sha256
    sha512
    echo "################################################################################"
    echo ""
  done
else
 until [ -z "$1" ]
  do
    file=$1
    for sumdo in $file
    do
      echo ""
      echo "################################################################################"
      echo "Sums for $sumdo"
      md5
      sha1
      sha256
      sha512
      echo "################################################################################"
      echo ""
    done
    shift
  done
fi
exit
