#!/usr/bin/env bash

tempdir="$(mktemp -d)"

echo "==> Downloading latest AWS CLI v2"
curl -sL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "${tempdir}/awscliv2.zip"

echo "==> Unzipping installer"
unzip -qq "${tempdir}/awscliv2.zip" -d "${tempdir}"

install_command=("aws/install")

if [ -n "$*" ]; then
    install_command+=("$@")
fi

if which "aws" > /dev/null 2>&1; then
    install_command+=("--update")
fi

echo "==> Executing installer"
echo "... ${install_command[*]}"
install_command[0]="${tempdir}/${install_command[0]}"
sudo -- "${install_command[@]}" | while read -r line; do
    echo "... $line"
done
version="$(aws --version | cut -d' ' -f1 | cut -d'/' -f2)"
echo "==> New version: $version"
