#!/usr/bin/env bash

set -e
tempdir="$(mktemp -d -t "awsupdate")"

trap 'cleanup $?' EXIT

cleanup() {
    if [[ "$VERBOSE" == "true" ]]; then
        echo "==> Cleaning up $tempdir"
    fi
    rm -rf "$tempdir"
}

echo "==> Downloading latest AWS CLI v2"
curl --silent --location "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" --output "${tempdir}/awscliv2.zip"

echo "==> Unzipping installer"
unzip -qq "${tempdir}/awscliv2.zip" -d "${tempdir}"

install_command=("aws/install")

if [ -n "$*" ]; then
    install_command+=("$@")
fi

if which "aws" > /dev/null 2>&1; then
    install_command+=("--update")
fi

echo "==> Executing installer: ${install_command[*]}"
install_command[0]="${tempdir}/${install_command[0]}"
sudo -- "${install_command[@]}" | while read -r line; do
    echo "... $line"
done
version="$(aws --version | cut -d' ' -f1 | cut -d'/' -f2)"
echo "==> New version: $version"
