#!/usr/bin/env bash

# This script provides general, useful infomation on login. Should be
# sourced from /etc/skel/.*shrc. Additionally, to use maintenance motd, the
# file /etc/motd-maint should be created.

#Define Variables
proccount=$(ps -l | wc -l)
proccount=$(( proccount - 4 ))
sessions=$(who | grep $USER | wc -l)

#Text formatting
Bold='\e[1m'
RCol='\e[0m'    # Text Reset
# Regular           Bold                Underline           High Intensity      BoldHigh Intens     Background          High Intensity Backgrounds
Bla='\e[0;30m';     BBla='\e[1;30m';    UBla='\e[4;30m';    IBla='\e[0;90m';    BIBla='\e[1;90m';   On_Bla='\e[40m';    On_IBla='\e[0;100m';
Red='\e[0;31m';     BRed='\e[1;31m';    URed='\e[4;31m';    IRed='\e[0;91m';    BIRed='\e[1;91m';   On_Red='\e[41m';    On_IRed='\e[0;101m';
Gre='\e[0;32m';     BGre='\e[1;32m';    UGre='\e[4;32m';    IGre='\e[0;92m';    BIGre='\e[1;92m';   On_Gre='\e[42m';    On_IGre='\e[0;102m';
Yel='\e[0;33m';     BYel='\e[1;33m';    UYel='\e[4;33m';    IYel='\e[0;93m';    BIYel='\e[1;93m';   On_Yel='\e[43m';    On_IYel='\e[0;103m';
Blu='\e[0;34m';     BBlu='\e[1;34m';    UBlu='\e[4;34m';    IBlu='\e[0;94m';    BIBlu='\e[1;94m';   On_Blu='\e[44m';    On_IBlu='\e[0;104m';
Pur='\e[0;35m';     BPur='\e[1;35m';    UPur='\e[4;35m';    IPur='\e[0;95m';    BIPur='\e[1;95m';   On_Pur='\e[45m';    On_IPur='\e[0;105m';
Cya='\e[0;36m';     BCya='\e[1;36m';    UCya='\e[4;36m';    ICya='\e[0;96m';    BICya='\e[1;96m';   On_Cya='\e[46m';    On_ICya='\e[0;106m';
Whi='\e[0;37m';     BWhi='\e[1;37m';    UWhi='\e[4;37m';    IWhi='\e[0;97m';    BIWhi='\e[1;97m';   On_Whi='\e[47m';    On_IWhi='\e[0;107m';

numupdates=$(pacman -Qu | wc -l)

if (( numupdates > 0 )); then
    updates=${BRed}${numupdates}${RCol}
else
    updates=${BGre}${numupdates}${RCol}
fi

#Begin output
echo -e "
+++++++++++++++++: ${Bold}System Data${RCol} :+++++++++++++++++++
      Hostname = ${BCya}$(hostname)${RCol}
       Address = ${Bold}$(ip a show dev wlp3s0 | grep -m1 inet | sed 's/^ *//g' | cut -d\  -f 2 | cut -d '/' -f 1 | sed 's/addr://g')${RCol}
        Kernel = $(uname -r)
        Uptime = $(uptime -p)
           CPU = $(cat /proc/cpuinfo | grep -m1 "model name" | cut -d: -f2 | sed 's/           / /g' | sed -e 's/^[[:space:]]*//') X $(nproc)
        Memory = $(cat /proc/meminfo | grep MemTotal | awk {'print $2'}) kB
 Updates Avail = ${updates}
++++++++++++++++++: ${Bold}User Data${RCol} :++++++++++++++++++++
      Username = $(whoami)
        Groups = $(id -Gn)
      Sessions = ${sessions}
     Processes = ${proccount}
+++++++++++++: ${Bold}Helpful Information${RCol} :+++++++++++++++
 Users logged in = ${BCya}$(users | tr ' ' '\n' | sort -u | wc -l)${RCol}
+++++++++++: ${Bold}Maintenance Information${RCol} :+++++++++++++
$(cat /etc/motd-maint 2> /dev/null  | while read maintline; do echo " ${Red}${maintline}${RCol}"; done)
+++++++++++++++++++++++++++++++++++++++++++++++++++
"
