#!/usr/bin/env bash

# This script provides general, useful infomation on login. Should be
# sourced from /etc/skel/.*shrc. Additionally, to use maintenance motd, the
# file /etc/motd-maint should be created.

#Define Variables
proccount=$(ps -l | wc -l)
proccount=$(( proccount - 4 ))
sessions="$(who | grep -c "$(id -urn)")"

#Text formatting
bold='\e[1m'
reset='\e[0m'
# Regular           bold
black='\e[0;30m';   bold_black='\e[1;30m';
red='\e[0;31m';     bold_red='\e[1;31m';
green='\e[0;32m';   bold_green='\e[1;32m';
yellow='\e[0;33m';  bold_yellow='\e[1;33m';
blue='\e[0;34m';    bold_blue='\e[1;34m';
purple='\e[0;35m';  bold_purple='\e[1;35m';
cyan='\e[0;36m';    bold_cyan='\e[1;36m';
white='\e[0;37m';   bold_white='\e[1;37m';

numupdates=$(pacman -Qu | wc -l)

if (( numupdates > 0 )); then
    updates=${bold_red}${numupdates}${reset}
else
    updates=${bold_green}${numupdates}${reset}
fi

function maint_motd_text() {
    echo -n "${red}"
    while read -r maintline; do
        echo " ${maintline}";
    done < /etc/motd-maint
    echo -n "${reset}"
}

#Begin output
echo 2>/dev/null "
+++++++++++++++++: ${bold}System Data${reset} :+++++++++++++++++++
      Hostname = ${bold_cyan}$(hostname)${reset}
       Address = ${bold}$(hostname -i)${reset}
        Kernel = $(uname -r)
        Uptime = $(uptime -p)
           CPU = $(awk -F": " '/model name/ {print $2;exit}' /proc/cpuinfo) X $(nproc)
        Memory = $(free -h | grep "Mem:" | awk '{print $2;}')
++++++++++++++++++: ${bold}User Data${reset} :++++++++++++++++++++
      Username = $(id -un)
        Groups = $(id -Gn)
      Sessions = ${sessions}
     Processes = ${proccount}
+++++++++++++: ${bold}Helpful Information${reset} :+++++++++++++++
Total user sessions = ${bold_cyan}$(users | wc -w)${reset}
  Updates Available = ${updates}
+++++++++++: ${bold}Maintenance Information${reset} :+++++++++++++
$(maint_motd_text)
+++++++++++++++++++++++++++++++++++++++++++++++++++
"
