#!/bin/bash

#License: MIT License https://raw.github.com/kalaker/useful_scripts/master/LICENSE
#Git Repo: https://github.com/kalaker/useful_scripts/

function md5(){
  echo "Generating MD5 sum for ${i}."
  md5sum "$i" > ${i}.md5
}

for i in $(find . -name "*.zip")
   do
      echo "$i"
      md5
    done
    shift
exit
