#!/usr/bin/env bash

# Update Arch mirrors based on the beginning of my public IP address.
# 134.126 = On campus, so use mirror.jmu.edu, otherwise, use the
# kernel.org mirrors

readonly jmu_mirror="http://mirror.jmu.edu/pub/"
readonly kernel_mirror="http://mirrors.kernel.org/"
readonly arch_path='archlinux/$repo/os/$arch'
readonly mirror_file="/etc/pacman.d/currentmirrors"
readonly ip_api="https://api.ipify.org"
readonly jmu_ip="134.126"

check_if_jmu() {
    local ip_address
    ip_address="$(curl -s "${ip_api}")"
    if [ "${ip_address#"$jmu_ip"}" != "${ip_address}" ]; then
        ip_is_jmu=true
    else
        ip_is_jmu=false
    fi
}

main() {
    check_if_jmu
    if [[ "${ip_is_jmu}" = true ]]; then
        readonly full_line="Server = ${jmu_mirror}${arch_path}"
    else
        readonly full_line="Server = ${kernel_mirror}${arch_path}"
    fi
    echo "$full_line" > "${mirror_file}"
}

main
